name: Cypress Tests

on:
  push:
    branches:
      - main
      - pipe-test

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]  # Defina a versão do Node.js que você quer usar

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run
